name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make tests
      run: make tests

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "LD_LIBRARY_PATH=./CUnit_container/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
    - name: run check
      uses: deep5050/cppcheck-action@main
      run : make check
